### ISSUE TITLE
High Performance TiDB | homework -2 

### ISSUE THREAD

**Issue by y4h2** [y4h2/blog#9]
# 节点信息
|  node-ip| 节点型号| 部署组件|
|---|---|---|
| 172.31.23.74  | CPU: 8 * (E5-2686 v4 @ 2.30GHz), Memory: 32GB, Disk: EBS | 1*TiDB + 1*TiFlash + 1*PD + monitoring|
| 172.31.19.136 | CPU: 8 * (E5-2686 v4 @ 2.30GHz), Memory: 32GB, Disk: EBS | 1*TiKV |
| 172.31.17.204 | CPU: 8 * (E5-2686 v4 @ 2.30GHz), Memory: 32GB, Disk: EBS | 1*TiKV | 
| 172.31.28.214 | CPU: 8 * (E5-2686 v4 @ 2.30GHz), Memory: 32GB, Disk: EBS | 1*TiKV |

![image](https://user-images.githubusercontent.com/5662692/91111486-a0553e00-e64e-11ea-9753-f9fefe911ff0.png)

# TiUP配置文件
```
# # Global variables are applied to all deployments and used as the default value of
# # the deployments if a specific deployment value is missing.
global:
 user: "tidb"
 ssh_port: 22
 deploy_dir: "/tidb-deploy"
 data_dir: "/tidb-data"

# # Monitored variables are applied to all the machines.
monitored:
 node_exporter_port: 9100
 blackbox_exporter_port: 9115

server_configs:
 tidb:
   log.slow-threshold: 300
 tikv:
   readpool.storage.use-unified-pool: false
   readpool.coprocessor.use-unified-pool: true
 pd:
   replication.enable-placement-rules: true
 tiflash:
   logger.level: "info"

pd_servers:
 - host: 172.31.23.74

tidb_servers:
 - host: 172.31.23.74

tikv_servers:
 - host: 172.31.19.136
   port: 20160
   status_port: 20180

 - host: 172.31.17.204
   port: 20161
   status_port: 20181

 - host: 172.31.28.214
   port: 20162
   status_port: 20182

tiflash_servers:
 - host: 172.31.23.74

monitoring_servers:
 - host: 172.31.23.74

grafana_servers:
 - host: 172.31.23.74
```

# sysbench测试

## point select
sysbench oltp_point_select --config-file=config --threads=32 --tables=32 --table_size=100000 prepare

Result
100,000数据, 128 threads, 16494.59 qps, 1030.91 tps
![image](https://user-images.githubusercontent.com/5662692/91111271-1907ca80-e64e-11ea-86f5-f713ea4bf928.png)

## update index
100,000数据, 128 threads, 4851.02 qps, 4851.02 tps
![image](https://user-images.githubusercontent.com/5662692/91111328-43f21e80-e64e-11ea-9af1-3ab80ecf22a7.png)

## read only
100,000数据, 128 threads, 16553.96 qps, 1034.62 tps
![image](https://user-images.githubusercontent.com/5662692/91111076-8ff09380-e64d-11ea-9bd6-a55f189b0071.png)

# go-ycsb
## workload a
![image](https://user-images.githubusercontent.com/5662692/91112421-18bcfe80-e651-11ea-8311-d5750f5cedd9.png)

## workload b
![image](https://user-images.githubusercontent.com/5662692/91112624-9b45be00-e651-11ea-93de-336acfd80006.png)

## workload c
![image](https://user-images.githubusercontent.com/5662692/91112661-b7495f80-e651-11ea-822d-e81f98fb41cf.png)

## workload d
![image](https://user-images.githubusercontent.com/5662692/91112706-d811b500-e651-11ea-8172-43595eb85593.png)

## workload e
![image](https://user-images.githubusercontent.com/5662692/91112746-ec55b200-e651-11ea-8526-daa1384b2d62.png)

## workload f
![image](https://user-images.githubusercontent.com/5662692/91112775-f8417400-e651-11ea-939b-431e339785ac.png)

# tpc

## tpcc
load 100 warehouse
测试运行 2 warehouse 10 thread, tpmc 2190.2
![image](https://user-images.githubusercontent.com/5662692/91118704-8a03ae00-e65f-11ea-99ce-5477dbf762bf.png)

2 warehouse 100 thread, tpmc 2384.4
![image](https://user-images.githubusercontent.com/5662692/91119047-507f7280-e660-11ea-8b2f-5fed315b657e.png)

100 warehouse 100 thread, tpmc 17649.8
![image](https://user-images.githubusercontent.com/5662692/91119127-7efd4d80-e660-11ea-95bf-bdbd2c6e81de.png)

## tpch
![image](https://user-images.githubusercontent.com/5662692/91120899-ab1acd80-e664-11ea-862f-c90d5df8da92.png)

# 监控截图
QPS
![image](https://user-images.githubusercontent.com/5662692/91121314-8410cb80-e665-11ea-84ba-01d2fb41d038.png)

# TiKV
![image](https://user-images.githubusercontent.com/5662692/91121403-b3bfd380-e665-11ea-981d-6f46ee1ce237.png)

![image](https://user-images.githubusercontent.com/5662692/91121367-9e4aa980-e665-11ea-8804-8355b0182877.png)

grpc
![image](https://user-images.githubusercontent.com/5662692/91121463-d5b95600-e665-11ea-9f35-07e8ae25648c.png)

# 分析
通过观察pprof分析图, 大概能看出parser, 即解析SQL语句时占用的时间较多, 可能原因是我只部署了一个TiDB节点, 但是部署了3个TiKV节点, 存储数据的速度远快于解析SQL的速度, 如果增加TiDB节点, 情况可能会有所改观.
tables (*TableCommon)AddRecord占用时间也比较多, 可能原因是频繁插入数据, 这个是内部的主要逻辑, 占用大量时间无可厚非.
其次是runtime的mallocgc和scanobject耗时较多, 可能原因是qps较高的情况下, 内部需要反复创建新object, 然后有GC的参与.
![image](https://user-images.githubusercontent.com/5662692/91121746-86275a00-e666-11ea-9f2a-8a985fe904e9.png)
![image](https://user-images.githubusercontent.com/5662692/91121776-9808fd00-e666-11ea-9817-218277894f73.png)
